---
title: "DATA 607 Project 1"
output: html_document
date: "2023-02-12"
---

## Load neccessary packages
```{r}
library(tidyverse)
```

## Data Analysis on Chess Players
For this project, a text file of chess tournament was given ([link](https://raw.githubusercontent.com/eddiexunyc/607_project_1/main/chess_tournment_data.txt)). An analysis will be conducted to provide the player's statistic and output it into a csv file.

## Read Text File
```{r}
chess_URL <-"https://raw.githubusercontent.com/eddiexunyc/607_project_1/main/chess_tournment_data.txt"

chess_data <-read.delim(chess_URL, skip =1, header = TRUE, sep = "|")

head(chess_data, 10)

```
```{r}
#check the data type of the dataframe
str(chess_data)

```

## Data Cleaning
```{r}
# remove the dash
chess_data <-chess_data[!grepl("-----------------------------------------------------------------------------------------", chess_data$Pair),]

# combine the 2 headers and delete a row
names(chess_data) <-paste(names(chess_data), chess_data[1, ], sep = "_")
chess_data <-chess_data[-1,]

# rename the column header
colnames(chess_data) <- c("Pair Num", "Player Name USCF ID/RTG(Pre>Post)", "Total Points", "Round 1", "Round 2", "Round 3", "Round 4", "Round 5", "Round 6", "Round 7")

knitr::kable(chess_data)

```
## Data Formating
```{r}
# split the data based on sequence
player_rating <- chess_data[seq(2, nrow(chess_data), 2),]
player_info <- chess_data[seq(1, nrow(chess_data), 2),]

# extract individual chess data
player_pre_rating <- str_sub_all(player_rating$`Player Name USCF ID/RTG(Pre>Post)`,15, 19)
player_uscf_id <- str_sub_all(player_rating$`Player Name USCF ID/RTG(Pre>Post)`,1, 8)
player_state <- str_sub_all(player_rating$`Pair Num`)
player_round <- lapply(player_info[,4:10], function(x) str_extract(x, '\\d+'))

# merge chess data into one dataframe
chess_sub_data <- data.frame(unlist(player_uscf_id), unlist(player_state), unlist(player_pre_rating), player_round)
chess_new_data <- cbind(player_info[,1:3], chess_sub_data)

# rename the column and reorder the column by name
colnames(chess_new_data) <- c("ID", "Player Name", "Total Points", "Player USCF ID", "Player State", "Player Pre-Rating", "Round 1", "Round 2", "Round 3", "Round 4", "Round 5", "Round 6", "Round 7")

knitr::kable(chess_new_data)
```
## Data Calculations
```{r}
# create a matrix and use a nested for loop to find and replace ID with Pre-rating
new_round <- chess_new_data[7:13]

match_round <- matrix(unlist(new_round), nrow = 64, ncol = 7)

for(x in 1:nrow(match_round)){
  
  for(y in 1:ncol(match_round)){
    
    if(!is.na(match_round[x, y])){ 
      index <- match_round[x, y] 
      index <- strtoi(index, base=0L) 
      match_round[x,y] = strtoi(player_pre_rating[index])

    }
  }
}

# change the matrix to a numeric data type
calc_round <- matrix(as.numeric(match_round), nrow = 64, ncol = 7)

# calculate the average of the opponent's pre-rating
chess_new_data['Opponent Avg Rating'] <- round(rowMeans(calc_round, na.rm = TRUE))

knitr::kable(chess_new_data)
```
```{r}
# create a output dataframe with selected data
chess_output <- subset(chess_new_data, select = c("Player Name", "Total Points", "Player State", "Player Pre-Rating", "Opponent Avg Rating"))

col_order <- c("Player Name", "Player State", "Total Points", "Player Pre-Rating", "Opponent Avg Rating")
chess_output <- chess_output[, col_order]

# export the dataframe to a CSV file
write.csv(chess_output, "final_chess.csv", row.names = FALSE)
knitr::kable(chess_output)

```

## ELO Calculation
```{r}
# extract the round status
player_round_status <- lapply(player_info[,4:10], function(y) str_extract(y, '\\D'))

#create a matrix and add point based on the round status
status_round <- matrix(unlist(player_round_status), nrow = 64, ncol = 7)

for(x in 1:nrow(status_round)){
  
  for(y in 1:ncol(status_round)){
    if(status_round[x,y] == "W"){
      index <- status_round[x,y]
      index <- strtoi(index, base=0L) 
      status_round[x,y] = "1"
    }
    else if(status_round[x,y] == "D"){
      index <- status_round[x,y]
      index <- strtoi(index, base=0L)
      status_round[x,y] = "0.5"
    }
    else if(status_round[x,y] == "L"){
      index <- status_round[x,y]
      index <- strtoi(index, base=0L)
      status_round[x,y] = "0"
    }
  }
}

```









